// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderingSystem.Server.Data;

#nullable disable

namespace OrderingSystem.Server.Migrations
{
    [DbContext(typeof(OrderDataContext))]
    [Migration("20240212151653_RemovePriceOrderClass")]
    partial class RemovePriceOrderClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderingSystem.Shared.Customer", b =>
                {
                    b.Property<string>("CustCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BillAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustCode");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OrderingSystem.Shared.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerCustCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("ProductProdCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerCustCode");

                    b.HasIndex("ProductProdCode");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderingSystem.Shared.Product", b =>
                {
                    b.Property<string>("ProdCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ProdCode");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OrderingSystem.Shared.Order", b =>
                {
                    b.HasOne("OrderingSystem.Shared.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerCustCode");

                    b.HasOne("OrderingSystem.Shared.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductProdCode");

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderingSystem.Shared.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderingSystem.Shared.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
